FROM quay.io/maherzubair/sigma-md:beta
RUN https://github.com/LUCKYSERSKBA/Quenn-Ziyav /root/LUCKYSERSKBA/XLICONV1
WORKDIR /root/LUCKYSERSKBA/XLICONV1/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
